### ISSUE TITLE
CustomRaidTimes: CONFIG_LOAD_ERROR - Could not load configuration[Bug]: 

### ISSUE THREAD

**Issue by Swervoleopard** [refringe/CustomRaidTimes#8]
### Discord Username

shamuvomited

### What happened?

have the same issue as the other guy spartan man

### SPT Version

3.8.0

### Server Log

```shell
balls
```

**Comment by refringe** [comment]
The CONFIG_LOAD_ERROR error happens when the program can not locate the configuration file. Make sure that the file is named `config.json5`, and not `config.json5.txt`. This could easily happen if you have file extentions hidden.

![image](https://github.com/refringe/CustomRaidTimes/assets/127057/da1b82df-1db1-4a9c-9f6f-d6a5665505ec)

Also, when you're editing a file in Notepad make sure you're saving it with the "all files" type and not the "text document" type.

![image](https://github.com/refringe/CustomRaidTimes/assets/127057/726788ee-30a4-49c9-9fcd-561af24cd061)

**Comment by refringe** [comment]
See #7 for further discussion.
